# .github/workflows/cd.yml
name: CD Pipeline

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  helm-package-and-deploy:
    name: Helm Package & Deploy
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: homelab
    steps:
      - uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set image tag from Git tag
        run: echo "IMAGE_TAG=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Deploy to Homelab K8s
        uses: azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: |
            deploy/charts/nutrition-tracker
          images: ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}